### ISSUE TITLE
NEW VOTER REG.

### ISSUE THREAD

**Issue by aditya6413** [jayeshbhandarkar/Web-Based-Online-Voting-System#2]
HOW NEW VOTERS WILL ASSIGN 
BECAUSE ITS ASKING OTP

**Comment by jayeshbhandarkar** [comment]
At first time when the user click on "Registered as Voter Option" , then it will assign that registered user as a voter. And at the time of login only it will asks for the OTP ( for verification purpose - to check whether the same user is only there to vote and not anybody else )

**Comment by jayeshbhandarkar** [comment]
At first time when the user click on "Registered as Voter Option" , then it will assign that registered user as a voter. And at the time of login only it will asks for the OTP ( for verification purpose - to check whether the same user is only there to vote and not anybody else )

**Comment by jayeshbhandarkar** [comment]
> HOW NEW VOTERS WILL ASSIGN BECAUSE ITS ASKING OTP

At first time when the user click on "Registered as Voter Option" , then it will assign that registered user as a voter. And at the time of login only it will asks for the OTP ( for verification purpose - to check whether the same user is only there to vote and not anybody else )
